### PR TITLE
Add details about v1.6.2

### PR DESCRIPTION
**Pull request by bennuttall**
...and correct docs referring to 1.6.0 as the last version supporting Python 2

### CODE REVIEW

**Comment by bennuttall** [comment]
Release from [branch v162](https://github.com/gpiozero/gpiozero/tree/v162) but merge these changes into master

**Comment by waveform80** [comment]
It might be better to simply state 1.6.x will be the final Python 2.x supporting release just in case there's anything else we need to fix up in this branch (critical bugs or what-not). Just implies that there won't be a 1.7.x with new features that still supports Python 2.x - basically critical bug fixes only for 1.6.x (any new features will be 2.x, etc.)

**Comment by bennuttall** [comment]
I did consider that... may as well - bear with me

**Comment by bennuttall** [comment]
Done

**Comment by bennuttall** [comment]
Just updated the wording on both branches

**Pull request merged**
