### PR TITLE
Add complete Pi4 support to NativePin. Fixes #895 and #777

### LINKED ISSUE #895: Pull-down issue with `NativeFactory` on a Pi 4
Operating system: Raspbian Buster
Python version: 3.7
Pi model: tested on Pi 3 and 4 Model B
GPIO Zero version: =1.5.1
Pin factory used: tested with RPiGPIO and Native

The code below is supposed to test pull up/down on a floating pin. It works correctly and outputs `0` and then `1`.

```python
from gpiozero.pins.rpigpio import RPiGPIOFactory
pin = RPiGPIOFactory().pin(5)
pin.function = 'input'
pin.pull = 'down'
print(pin.state)
pin.pull = 'up'
print(pin.state)
```

Changing the factory to `NativeFactory` still works correctly on a Raspberry Pi <4. The code below outputs `False` and then `True`.

```python
from gpiozero.pins.native import NativeFactory
pin = NativeFactory().pin(6)
pin.function = 'input'
pin.pull = 'down'
print(pin.state)
pin.pull = 'up'
print(pin.state)
```
However, on a Pi 4 it will output `True` and `True`. It seems the Pi 4 uses a different pull register and the `NativeFactory` might need to be updated to reflect that.

### PR DESCRIPTION
**Pull request by lurch**
Also add more comprehensive pull-state tests.

**MUCH** overdue, but I finally got round to dusting off, polishing and testing my old patch for NativePin support for Pi4 :tada: 

Tested on: Pi 1A, Pi 1A+, Pi Zero WH, Pi 2B, Pi 3A+, Pi 4B. (the testing felt like it took longer than the coding!)

### CODE REVIEW

**Comment by lnussbaum** [comment]
Hi,
I'm testing this PR on a RPI4 running in 64bits mode on the vanilla (kernel.org) Linux kernel.

it does not work for me. For example, with this example:
```python
from gpiozero import LED
from time import sleep

red = LED(17)

while True:
    red.on()
    sleep(1)
    red.off()
    sleep(1)
```

I get:
```
/usr/lib/python3/dist-packages/gpiozero/devices.py:289: PinFactoryFallback: Falling back from rpigpio: No module named 'RPi'
  'Falling back from %s: %s' % (name, str(e))))
/usr/lib/python3/dist-packages/gpiozero/devices.py:289: PinFactoryFallback: Falling back from rpio: No module named 'RPIO'
  'Falling back from %s: %s' % (name, str(e))))
/usr/lib/python3/dist-packages/gpiozero/devices.py:289: PinFactoryFallback: Falling back from pigpio: No module named 'pigpio'
  'Falling back from %s: %s' % (name, str(e))))
/usr/lib/python3/dist-packages/gpiozero/devices.py:284: NativePinFactoryFallback: Falling back to the experimental pin factory NativeFactory because no other pin factory could be loaded. For best results, install RPi.GPIO or pigpio. See https://gpiozero.readthedocs.io/en/stable/api_pins.html for more information.
  warnings.warn(NativePinFactoryFallback(native_fallback_message))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 109, in pin
    pin = self.pins[n]
KeyError: 17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t2.py", line 4, in <module>
    red = LED(17)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 131, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 217, in __init__
    pin, active_high, initial_value, pin_factory=pin_factory
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 99, in __init__
    super(OutputDevice, self).__init__(pin, pin_factory=pin_factory)
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 106, in __init__
    super(SourceMixin, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 545, in __init__
    pin = self.pin_factory.pin(pin)
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 111, in pin
    pin = self.pin_class(self, n)
  File "/usr/lib/python3/dist-packages/gpiozero/pins/native.py", line 437, in __init__
    self.pull = 'up' if self.factory.pi_info.pulled_up(repr(self)) else 'floating'
  File "/usr/lib/python3/dist-packages/gpiozero/pins/__init__.py", line 337, in <lambda>
    lambda self, value: self._set_pull(value),
  File "/usr/lib/python3/dist-packages/gpiozero/pins/native.py", line 482, in _set_pull
    raise PinFixedPull('cannot set pull on non-input pin %r' % self)
gpiozero.exc.PinFixedPull: cannot set pull on non-input pin GPIO17
```

Any ideas?

**Comment by lurch** [comment]
Hmmm, I hadn't tested on a 64-bit kernel... but looking through the Python code in GpioZero I can't see how it'd be any different.
I tried your example above on a standard 32-bit Raspberry Pi OS (whilst forcing the use of the [native](https://gpiozero.readthedocs.io/en/master/api_pins.html#changing-the-pin-factory) pin factory), and it worked fine. Looking at your traceback, it's throwing an error from https://github.com/gpiozero/gpiozero/blob/29ea84d0176aec18469b1fc8535dcfd36958719d/gpiozero/pins/native.py#L482 but that error only triggers if `self.function != 'input'`. And that `_set_pull` function (it's a property-setter) is called by https://github.com/gpiozero/gpiozero/blob/29ea84d0176aec18469b1fc8535dcfd36958719d/gpiozero/pins/native.py#L437 which is done immediately after `self.function = 'input'` - all very weird! :confused: 

I'll try to find time to test on the beta 64-bit version of Raspberry Pi OS this evening.

**Comment by lnussbaum** [comment]
Note that I'm also running on a vanilla kernel (not a Raspberry Pi OS one). So /dev/gpiomem is not available, and gpiozero needs to use /dev/mem (with the magic to discover the GPIO address range). It might be another source of issue.

You can probably emulate this setup by removing /dev/gpiomem on the Raspberry Pi OS.

**Comment by drewrisinger** [comment]
Linking related issues to find this PR easier from the issues: #895 #777

**Comment by waveform80** [comment]
Continued in #929 (many thanks for @lurch for this! I'm just closing this PR to continue this branch after rebase and a little re-working)

**Comment by lurch** [comment]
@lnussbaum This issue has now been closed, so if you're still having problems you should open a separate issue.

**Pull request closed without merging**
