### PR TITLE
Rotate option - to rotate pinout 180 degrees

### PR DESCRIPTION
**Pull request by chrisruk**
I would be interested in improving this, by not using a global variable, the difficulty I found being that you can't add additional parameters to __format__ calls as far as I understand.

Example pinout:

```
J8:
   3V3  (1) (2)  5V    
 GPIO2  (3) (4)  5V    
 GPIO3  (5) (6)  GND   
 GPIO4  (7) (8)  GPIO14
   GND  (9) (10) GPIO15
GPIO17 (11) (12) GPIO18
GPIO27 (13) (14) GND   
GPIO22 (15) (16) GPIO23
   3V3 (17) (18) GPIO24
GPIO10 (19) (20) GND   
 GPIO9 (21) (22) GPIO25
GPIO11 (23) (24) GPIO8 
   GND (25) (26) GPIO7 
 GPIO0 (27) (28) GPIO1 
 GPIO5 (29) (30) GND   
 GPIO6 (31) (32) GPIO12
GPIO13 (33) (34) GND   
GPIO19 (35) (36) GPIO16
GPIO26 (37) (38) GPIO20
   GND (39) (40) GPIO21
```

Rotated pinout:
```
J8:
(40) GPIO21    GND (39)
(38) GPIO20 GPIO26 (37)
(36) GPIO16 GPIO19 (35)
(34) GND    GPIO13 (33)
(32) GPIO12  GPIO6 (31)
(30) GND     GPIO5 (29)
(28) GPIO1   GPIO0 (27)
(26) GPIO7     GND (25)
(24) GPIO8  GPIO11 (23)
(22) GPIO25  GPIO9 (21)
(20) GND    GPIO10 (19)
(18) GPIO24    3V3 (17)
(16) GPIO23 GPIO22 (15)
(14) GND    GPIO27 (13)
(12) GPIO18 GPIO17 (11)
(10) GPIO15    GND  (9)
(8)  GPIO14  GPIO4  (7)
(6)  GND     GPIO3  (5)
(4)  5V      GPIO2  (3)
(2)  5V        3V3  (1)
```

### CODE REVIEW

**Comment by bennuttall** [comment]
Sounds good. It was suggested in #723 and someone started working on it at a pycon sprint - it was basically finished but they never submitted a PR :(

Looking forward to it

**Comment by lurch** [comment]
Wouldn't the rotated pinout look better with the pin-numbers down the middle rather than down the outside?

**Comment by lurch** [comment]
Looking at the code, you might be able to avoid using a global variable by using the Style / format_spec stuff? But unfortunately that's all semi-magic @waveform80 python code... :confused:  (i.e. hard to decipher :wink: )

**Comment by chrisruk** [comment]
Yep good point about the numbering being in the middle, I've just fixed that. 

Will have a look more at the style / format_spec

**Comment by waveform80** [comment]
This is a nice idea, but the wrong  way of going about it; it is possible to customize format-specs -- in fact that's exactly what the current code does -- and that's probably what we ought to do here (add some parameters to the format spec to optionally specify rotation of the output).

However, I'm not convinced my current custom format-spec code is terribly good. The custom format-spec isn't well thought out and, while I've been playing with it to add some more utilities I've come to the conclusion it's one of those areas that needs a serious re-write in 2.x. It's also an opportunity to expand PinInfo to include details of the alternative functions of pins (so users can actually query "which are the hardware SPI pins" for example).

Anyway, I'm going to close this PR, but only because it's the wrong approach: the idea is good and is something I'll certainly incorporate into the re-write.

**Pull request closed without merging**
